name: Build Signed APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Decode keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/keystore.p12
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Make gradlew executable if present
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Build Release APK
        run: |
          if [ -f ./gradlew ]; then ./gradlew assembleRelease --no-daemon; else gradle assembleRelease --no-daemon; fi

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
